function(mania_generate_embedded FRONTEND_DIST OUT_DIR)
  file(MAKE_DIRECTORY "${OUT_DIR}")
  if(NOT EXISTS "${FRONTEND_DIST}")
    file(WRITE "${OUT_DIR}/embedded_files.h"
         "#pragma once\n#define MANIA_HAS_EMBEDDED 0\n")
    file(WRITE "${OUT_DIR}/mania_resources.rc"
         "// no embedded frontend resources\n")
    return()
  endif()

  file(GLOB_RECURSE DIST_FILES "${FRONTEND_DIST}/*")
  set(RC_LINES "// generated by embed_frontend.cmake\n#include \"winres.h\"\n")
  set(MAP_ENTRIES)
  set(INDEX 0)
  foreach(FILE ${DIST_FILES})
    file(RELATIVE_PATH REL "${FRONTEND_DIST}" "${FILE}")
    string(REPLACE "\\" "/" REL_POSIX "${REL}")
    math(EXPR ID "100 + ${INDEX}")
    set(MIME "application/octet-stream")
    if(REL_POSIX MATCHES "\\.html?$")
      set(MIME "text/html")
    elseif(REL_POSIX MATCHES "\\.js$")
      set(MIME "text/javascript")
    elseif(REL_POSIX MATCHES "\\.css$")
      set(MIME "text/css")
    elseif(REL_POSIX MATCHES "\\.svg$")
      set(MIME "image/svg+xml")
    elseif(REL_POSIX MATCHES "\\.png$")
      set(MIME "image/png")
    elseif(REL_POSIX MATCHES "\\.jpe?g$")
      set(MIME "image/jpeg")
    elseif(REL_POSIX MATCHES "\\.webp$")
      set(MIME "image/webp")
    elseif(REL_POSIX MATCHES "\\.gif$")
      set(MIME "image/gif")
    elseif(REL_POSIX MATCHES "\\.bmp$")
      set(MIME "image/bmp")
    elseif(REL_POSIX MATCHES "\\.ico$")
      set(MIME "image/x-icon")
    elseif(REL_POSIX MATCHES "\\.woff2?$")
      set(MIME "font/woff")
    elseif(REL_POSIX MATCHES "\\.json$")
      set(MIME "application/json")
    endif()
    list(APPEND RC_LINES "${ID} RCDATA \"${FILE}\"")
    list(APPEND MAP_ENTRIES
         "  {\"${REL_POSIX}\", ${ID}, \"${MIME}\"},")
    math(EXPR INDEX "${INDEX} + 1")
  endforeach()

  string(JOIN "\n" RC_TEXT ${RC_LINES})
  file(WRITE "${OUT_DIR}/mania_resources.rc" "${RC_TEXT}\n")

  string(JOIN "\n" MAP_TEXT ${MAP_ENTRIES})
  string(CONCAT HEADER_CONTENT
         "#pragma once\n"
         "#include <string_view>\n"
         "#define MANIA_HAS_EMBEDDED ${INDEX}\n"
         "struct EmbeddedFile { const char* path; int id; const char* mime; };\n"
         "inline const EmbeddedFile kEmbeddedFiles[] = {\n"
         "${MAP_TEXT}\n"
         "};\n"
         "inline const EmbeddedFile* maniaEmbeddedFile(std::string_view path) {\n"
         "  for (const auto& file : kEmbeddedFiles) {\n"
         "    if (path == file.path) return &file;\n"
         "  }\n"
         "  return nullptr;\n"
         "}\n")
  file(WRITE "${OUT_DIR}/embedded_files.h" "${HEADER_CONTENT}")
endfunction()
